server.port=8082
spring.application.name=auth-service

# Eureka server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# PostgreSQL Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_service_db
spring.datasource.username=postgres
spring.datasource.password=@msdDhoni07

# JPA ORM Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT (later for login and refresh token)
jwt.secret=Xv93Jks8Nn5pQeL9d3WzQ9CkLz61PFTgFbRZ8x0Vb8k=
jwt.expiration=3600000
# JWT Refresh Token Expiration
jwt.refreshExpirationMs=86400000 

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

