server.port=8082
spring.application.name=auth-service

# Eureka server (keep pointing to your discovery-server URL)
eureka.client.service-url.defaultZone=http://discovery-service-ja7h.onrender.com/eureka

# PostgreSQL Database Config (Render internal DB)
spring.datasource.url=jdbc:postgresql://dpg-d4pufam3jp1c7397q1ag-a:5432/authdb_h6cg
spring.datasource.username=authdb_h6cg_user
spring.datasource.password=2isZgp5m277WHMze7zpdlLaYMXLsVn9S
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA ORM Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=Xv93Jks8Nn5pQeL9d3WzQ9CkLz61PFTgFbRZ8x0Vb8k=
jwt.expiration=3600000
jwt.refreshExpirationMs=86400000

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
