# =========================
# Server Configuration
# =========================
server.port=8093
spring.application.name=cart-service

# =========================
# Redis Configuration
# =========================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000

# Optional Redis database index (default is 0)
spring.data.redis.database=0

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=cart-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer


# Optional: set a keyspace prefix for your microservice (useful if multiple services use same Redis)
spring.data.redis.keyspace-prefix=cart-service:

# =========================
# Logging (optional but useful for debugging)
# =========================
logging.level.org.springframework.data.redis=DEBUG

# =========================
# Eureka Client Configuration
# =========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
